version: "3.9"
services:
  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage

  embedding_service:
    image: ghcr.io/korjavin/ragtgbot-embedding-service
    ports:
      - "8000:8000"
    restart: always
    depends_on:
      - qdrant

  tgbot:
    image: ghcr.io/korjavin/ragtgbot-tgbot
    restart: always
    depends_on:
      - qdrant
      - embedding_service
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - EMBEDDING_SERVICE_ADDRESS=http://embedding_service:8000/embeddings
      - QDRANT_SERVICE_ADDRESS=http://qdrant:6333

volumes:
  qdrant_data: