pdoversion: "3.9"
services:
  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage

  embedding_service:
    build: ./embedding_service
    ports:
      - "8000:8000"
    volumes:
      - ./embedding_service:/app
    depends_on:
      - qdrant

volumes:
  qdrant_data: